### PR TITLE
Make the output a little more human readable

### PR DESCRIPTION
**Pull request by joshkurien**

### CODE REVIEW

**Comment by joshkurien** [comment]
I'm not that well versed with python, so feel free to correct me :)

**Comment by Guilospanck** [comment]
It was nice, bro! I did this just to use the information in another application of mine, so the data was formatted to fill into this other application. Thanks!

**Comment by joshkurien** [comment]
Cool, please feel free to close the request and if you are using another application, which one is it??

**Comment by Guilospanck** [comment]
> Cool, please feel free to close the request and if you are using another application, which one is it??

I've created a simple react native app to gather this information e display to the user. I'm using a server running the python script every day at 03:30am so the list stays updated with the dotabuff website. Just for fun and training skills.
WhatsApp Image 2020-10-26 at 21 58 00

**Pull request closed without merging**
